<?php

namespace CarBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{

    public function findCarsWithDetails() {
        // createQueryBuilder() automatically selects FROM AppBundle:Car
        // and aliases it to "c"
        // http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/query-builder.html
        $qb = $this->createQueryBuilder('c');
        $qb->select('c, make, model');
        $qb->join('c.make', 'make');
        $qb->join('c.model', 'model');
        return $qb->getQuery()->getResult();
    }

    public function findCarsWithDetailsById($id) {
        // get single result
        $qb = $this->createQueryBuilder('c');
        $qb->select('c, make, model');
        $qb->join('c.make', 'make');
        $qb->join('c.model', 'model');
        $qb->where('c.id = :id');
        $qb->setParameter('id', $id);
        return $qb->getQuery()->getSingleResult();
    }

}
