<?php

namespace CarBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCarsWithDetails() {
        $qb = $this->createQueryBuilder('c');
        $qb->select('c');
        $qb->join('c.make', 'make');
        $qb->join('c.model', 'model');
        return $qb->getQuery()->getResult();
    }
}
